[project]
name = "langchain-learning"
version = "0.1.0"
description = "LangChain + LangGraph + LangSmith"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain",
    "langgraph",
    "langsmith",
    "langchain-openai",
    "python-dotenv",
]